name: Generate Mod Pages

on:
  push:
    branches:
      - main # または master（使用しているデフォルトブランチ名）
    paths:
      - 'resources/**'
      - 'template.html'
      - 'generate.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run generate.js
        run: node generate.js

      - name: Commit and Push generated pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: Generate mod pages [skip ci]"
          file_pattern: 'mods/**'
